# Standard Flutter Podfile
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously during install.
# If you're behind a firewall or have a slow network, this can cause a timeout.
# Uncomment and set the value to true to disable it.
# disable_cocoapods_analytics!

install! 'cocoapods', :deterministic_uuids => false

# Flutter's iOS instructions require this line.
flutter_ios_podfile_setup = File.join(File.dirname(File.realpath(__FILE__)), '.flutter-plugins-dependencies')
if File.exist?(flutter_ios_podfile_setup)
  require flutter_ios_podfile_setup
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
